package com.kotlinblo.blogspot.util

const val RUNNING_DATABASE_NAME="running_db"
const val REQUEST_CODE_LOCATION_PERMISION=0
const val ACTION_START_OR_RESUME_SERVICE="ACTION_START_OR_RESUME_SERVICE"
const val ACTION_PAUSE_SERVICE="ACTION_PAUSE_SERVICE"
const val ACTION_STOP_SERVICE="ACTION_STOP_SERVICE"